engines:
  scss-lint:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
ratings:
  paths:
  - src/**/*.js
exclude_paths:
- dist/**/*
- dist/*
- compile/**/*
- vendors/**/*
- vendors/*
- docsrc/**/*
- demos/**/*
- tests/**/*
- tasks/**/*
- docs/**/*
